'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Coder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("db", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property db1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("db1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_VisualBasic_PowerPacks_Vs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_VisualBasic_PowerPacks_Vs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.VisualBasic.PowerPacks.Vs&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.VisualBasic.PowerPacks.BackStyle&quot;&gt;
        '''      &lt;summary&gt;
        '''          Specifies the background transparency for an &lt;see cref=&quot;T:Microsoft.VisualBasic.PowerPacks.OvalShape&quot; /&gt; or &lt;see cref=&quot;T:Microsoft.VisualBasic.PowerPacks.RectangleShape&quot; /&gt; control.
        '''        &lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;F:Microsoft.VisualBasic.PowerPacks.BackS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_VisualBasic_PowerPacks_Vs1() As String
            Get
                Return ResourceManager.GetString("Microsoft_VisualBasic_PowerPacks_Vs1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_VisualBasic_PowerPacks_Vs2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_VisualBasic_PowerPacks_Vs2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.VisualBasic.PowerPacks.Vs&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.VisualBasic.PowerPacks.BackStyle&quot;&gt;
        '''      &lt;summary&gt;
        '''          Specifies the background transparency for an &lt;see cref=&quot;T:Microsoft.VisualBasic.PowerPacks.OvalShape&quot; /&gt; or &lt;see cref=&quot;T:Microsoft.VisualBasic.PowerPacks.RectangleShape&quot; /&gt; control.
        '''        &lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;F:Microsoft.VisualBasic.PowerPacks.BackS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_VisualBasic_PowerPacks_Vs3() As String
            Get
                Return ResourceManager.GetString("Microsoft_VisualBasic_PowerPacks_Vs3", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
